package pojos;
// Generated 03-jun-2025 20:06:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal stock;
     private String unidad;
     private BigDecimal umbralAlerta;
     private Set alertas = new HashSet(0);
     private Set platoIngredientes = new HashSet(0);

    public Ingrediente() {
    }

	
    public Ingrediente(String nombre, BigDecimal stock, String unidad, BigDecimal umbralAlerta) {
        this.nombre = nombre;
        this.stock = stock;
        this.unidad = unidad;
        this.umbralAlerta = umbralAlerta;
    }
    public Ingrediente(String nombre, BigDecimal stock, String unidad, BigDecimal umbralAlerta, Set alertas, Set platoIngredientes) {
       this.nombre = nombre;
       this.stock = stock;
       this.unidad = unidad;
       this.umbralAlerta = umbralAlerta;
       this.alertas = alertas;
       this.platoIngredientes = platoIngredientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public BigDecimal getUmbralAlerta() {
        return this.umbralAlerta;
    }
    
    public void setUmbralAlerta(BigDecimal umbralAlerta) {
        this.umbralAlerta = umbralAlerta;
    }
    public Set getAlertas() {
        return this.alertas;
    }
    
    public void setAlertas(Set alertas) {
        this.alertas = alertas;
    }
    public Set getPlatoIngredientes() {
        return this.platoIngredientes;
    }
    
    public void setPlatoIngredientes(Set platoIngredientes) {
        this.platoIngredientes = platoIngredientes;
    }




}


