package pojos;
// Generated 03-jun-2025 20:06:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PlatoIngrediente generated by hbm2java
 */
public class PlatoIngrediente  implements java.io.Serializable {


     private Integer id;
     private Ingrediente ingrediente;
     private Plato plato;
     private BigDecimal cantidad;

    public PlatoIngrediente() {
    }

	
    public PlatoIngrediente(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public PlatoIngrediente(Ingrediente ingrediente, Plato plato, BigDecimal cantidad) {
       this.ingrediente = ingrediente;
       this.plato = plato;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ingrediente getIngrediente() {
        return this.ingrediente;
    }
    
    public void setIngrediente(Ingrediente ingrediente) {
        this.ingrediente = ingrediente;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


